# Generated by Django 6.0.1 on 2026-04-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appoinment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=100)),
                ('appointment_date', models.DateField()),
                ('time_slot', models.CharField(choices=[('09:00 AM - 10:00 AM', '09:00 AM - 10:00 AM'), ('10:00 AM - 11:00 AM', '10:00 AM - 11:00 AM'), ('11:00 AM - 12:00 PM', '11:00 AM - 12:00 PM'), ('12:00 PM - 01:00 PM', '12:00 PM - 01:00 PM'), ('01:00 PM - 02:00 PM', '01:00 PM - 02:00 PM'), ('02:00 PM - 03:00 PM', '02:00 PM - 03:00 PM'), ('03:00 PM - 04:00 PM', '03:00 PM - 04:00 PM'), ('04:00 PM - 05:00 PM', '04:00 PM - 05:00 PM'), ('05:00 PM - 06:00 PM', '05:00 PM - 06:00 PM')], max_length=20)),
                ('problem', models.TextField()),
            ],
        ),
    ]
