# Generated by Django 6.0.1 on 2026-02-21 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appoinment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=100)),
                ('appointment_date', models.DateField()),
                ('time_slot', models.CharField(choices=[('1', '9:00 AM'), ('2', '10:00 AM'), ('3', '11:00 AM'), ('4', '4:00 PM'), ('5', '5:00 PM')], max_length=10)),
                ('problem', models.TextField()),
            ],
        ),
    ]
