# Generated by Django 6.0.1 on 2026-02-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appoinments', '0005_alter_appoinment_time_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinment',
            name='time_slot',
            field=models.CharField(choices=[('09:00 AM - 10:00 AM', '09:00 AM - 10:00 AM'), ('10:00 AM - 11:00 AM', '10:00 AM - 11:00 AM'), ('11:00 AM - 12:00 PM', '11:00 AM - 12:00 PM'), ('12:00 PM - 01:00 PM', '12:00 PM - 01:00 PM'), ('01:00 PM - 02:00 PM', '01:00 PM - 02:00 PM'), ('02:00 PM - 03:00 PM', '02:00 PM - 03:00 PM'), ('03:00 PM - 04:00 PM', '03:00 PM - 04:00 PM'), ('04:00 PM - 05:00 PM', '04:00 PM - 05:00 PM'), ('05:00 PM - 06:00 PM', '05:00 PM - 06:00 PM')], max_length=20),
        ),
    ]
